services:
  - type: web
    name: kaayjob-backend
    env: docker
    dockerfilePath: backend/Dockerfile.render
    dockerCommand: sh -c "npx prisma migrate deploy && node dist/index.js"
    envVars:
      - key: DATABASE_URL
        value: postgres://b9a0969b382808c1926482e10fd5a854e2fd7e020e81a9f3cc96e2885408ee95:sk_wqQoOr0QtZD7DSoDVsjPm@db.prisma.io:5432/postgres?sslmode=require
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://kaayjob.vercel.app

# Supprimé - utilisez votre base de données existante
# databases:
#   - name: kaayjob
#     plan: free
#     databaseName: kaayjob
