import {
  Hammer,
  Wrench,
  Truck,
  Car,
  Home,
  Building,
  Building2,
  User,
  Users,
  Briefcase,
  ShoppingCart,
  Heart,
  Stethoscope,
  Thermometer,
  Pill,
  CreditCard,
  Banknote,
  Wallet,
  Coffee,
  UtensilsCrossed,
  Pizza,
  Wine,
  Cake,
  Apple,
  Droplet,
  Flame,
  Snowflake,
  Sun,
  Moon,
  Cloud,
  CloudRain,
  Wind,
  Zap,
  Lightbulb,
  Plug,
  Battery,
  Gauge,
  Bus,
  Train,
  Plane,
  Ship,
  Anchor,
  MapPin,
  Navigation,
  Compass,
  Globe,
  Camera,
  Video,
  Music,
  Mic,
  Headphones,
  Volume2,
  Speaker,
  Monitor,
  Laptop,
  Smartphone,
  Tablet,
  Wifi,
  Phone,
  Mail,
  MessageSquare,
  FileText,
  File,
  Folder,
  Archive,
  Printer,
  Scissors,
  PenTool,
  Brush,
  Palette,
  Code,
  Database,
  Server,
  HardDrive,
  Cpu,
  Bot,
  Sparkles,
  Wand2,
  PaintBucket,
  Ruler,
  Clipboard,
  Calendar,
  Clock,
  Timer,
  Flag,
  Tag,
  Tags,
  Award,
  Trophy,
  Crown,
  Star,
  ThumbsUp,
  ThumbsDown,
  Smile,
  Frown,
  Laugh,
  PartyPopper,
  Gift,
  Ticket,
  Film,
  Dumbbell,
  Bike,
  Footprints,
  Scroll,
  BookOpen,
  Book,
  GraduationCap,
  Pencil,
  Check,
  X,
  Plus,
  Minus,
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  Menu,
  List,
  Filter,
  Settings,
  Search,
  ZoomIn,
  ZoomOut,
  Maximize,
  Minimize2,
  ExternalLink,
  Share,
  Inbox,
  Save,
  Trash2,
  RotateCcw,
  RotateCw,
  RefreshCw,
  Play,
  Pause,
  Square,
  Circle,
  Triangle,
  Hexagon,
  CheckCircle,
  XCircle,
  AlertTriangle,
  AlertCircle,
  Info,
  HelpCircle,
  Eye,
  EyeOff,
  Lock,
  Unlock,
  Key,
  Shield,
  ShieldCheck,
  Bug,
  Target,
  Crosshair,
  Activity,
  Bed,
  TrendingUp,
  TrendingDown,
  Leaf,
  TreeDeciduous,
  Flower2,
  Grid,
  MoreVertical,
  MoreHorizontal,
  Layers,
  Box,
  Package,
  Palmtree,
  Waves,
} from "lucide-react";

interface IconRendererProps {
  name: string;
  className?: string;
  defaultIcon?: React.ElementType;
}

const ICON_MAP: Record<string, React.ElementType> = {
  hammer: Hammer,
  wrench: Wrench,
  truck: Truck,
  car: Car,
  home: Home,
  building: Building,
  building2: Building2,
  user: User,
  users: Users,
  briefcase: Briefcase,
  shoppingcart: ShoppingCart,
  heart: Heart,
  stethoscope: Stethoscope,
  thermometer: Thermometer,
  pill: Pill,
  creditcard: CreditCard,
  banknote: Banknote,
  wallet: Wallet,
  coffee: Coffee,
  utensils: UtensilsCrossed,
  pizza: Pizza,
  wine: Wine,
  cake: Cake,
  apple: Apple,
  droplet: Droplet,
  flame: Flame,
  snowflake: Snowflake,
  sun: Sun,
  moon: Moon,
  cloud: Cloud,
  cloudrain: CloudRain,
  wind: Wind,
  zap: Zap,
  lightbulb: Lightbulb,
  plug: Plug,
  battery: Battery,
  gauge: Gauge,
  bus: Bus,
  train: Train,
  plane: Plane,
  ship: Ship,
  anchor: Anchor,
  mappin: MapPin,
  navigation: Navigation,
  compass: Compass,
  globe: Globe,
  camera: Camera,
  video: Video,
  music: Music,
  mic: Mic,
  headphones: Headphones,
  volume2: Volume2,
  speaker: Speaker,
  monitor: Monitor,
  laptop: Laptop,
  smartphone: Smartphone,
  tablet: Tablet,
  wifi: Wifi,
  phone: Phone,
  mail: Mail,
  messagesquare: MessageSquare,
  filetext: FileText,
  file: File,
  folder: Folder,
  archive: Archive,
  printer: Printer,
  scissors: Scissors,
  pentool: PenTool,
  brush: Brush,
  palette: Palette,
  code: Code,
  database: Database,
  server: Server,
  harddrive: HardDrive,
  cpu: Cpu,
  bot: Bot,
  sparkles: Sparkles,
  wand2: Wand2,
  paintbucket: PaintBucket,
  ruler: Ruler,
  clipboard: Clipboard,
  calendar: Calendar,
  clock: Clock,
  timer: Timer,
  flag: Flag,
  tag: Tag,
  tags: Tags,
  award: Award,
  trophy: Trophy,
  crown: Crown,
  star: Star,
  thumbsup: ThumbsUp,
  thumbsdown: ThumbsDown,
  smile: Smile,
  frown: Frown,
  laugh: Laugh,
  partyPopper: PartyPopper,
  gift: Gift,
  ticket: Ticket,
  film: Film,
  dumbbell: Dumbbell,
  bike: Bike,
  footprints: Footprints,
  scroll: Scroll,
  bookopen: BookOpen,
  book: Book,
  graduationcap: GraduationCap,
  pencil: Pencil,
  check: Check,
  x: X,
  plus: Plus,
  minus: Minus,
  arrowup: ArrowUp,
  arrowdown: ArrowDown,
  arrowleft: ArrowLeft,
  arrowright: ArrowRight,
  menu: Menu,
  list: List,
  filter: Filter,
  settings: Settings,
  search: Search,
  zoomin: ZoomIn,
  zoomout: ZoomOut,
  maximize: Maximize,
  minimize: Minimize2,
  externallink: ExternalLink,
  share: Share,
  inbox: Inbox,
  save: Save,
  trash2: Trash2,
  rotateCcw: RotateCcw,
  rotateCw: RotateCw,
  refreshCw: RefreshCw,
  play: Play,
  pause: Pause,
  square: Square,
  circle: Circle,
  triangle: Triangle,
  hexagon: Hexagon,
  checkcircle: CheckCircle,
  xcircle: XCircle,
  alerttriangle: AlertTriangle,
  alertcircle: AlertCircle,
  info: Info,
  helpcircle: HelpCircle,
  eye: Eye,
  eyeoff: EyeOff,
  lock: Lock,
  unlock: Unlock,
  key: Key,
  shield: Shield,
  shieldcheck: ShieldCheck,
  bug: Bug,
  target: Target,
  crosshair: Crosshair,
  activity: Activity,
  bed: Bed,
  trendingup: TrendingUp,
  trendingdown: TrendingDown,
  leaf: Leaf,
  tree: TreeDeciduous,
  flower2: Flower2,
  grid: Grid,
  morevertical: MoreVertical,
  morehorizontal: MoreHorizontal,
  layers: Layers,
  box: Box,
  package: Package,
  palmtree: Palmtree,
  waves: Waves,
};

export function IconRenderer({ name, className, defaultIcon: DefaultIcon }: IconRendererProps) {
  const IconComponent = ICON_MAP[name] || DefaultIcon || Folder;
  return <IconComponent className={className} />;
}

export { ICON_MAP };