import { useState } from "react";
import {
  Hammer,
  Wrench,
  Truck,
  Car,
  Home,
  Building,
  Building2,
  User,
  Users,
  Briefcase,
  ShoppingCart,
  Heart,
  Stethoscope,
  Thermometer,
  Pill,
  CreditCard,
  Banknote,
  Wallet,
  Coffee,
  UtensilsCrossed,
  Pizza,
  Wine,
  Cake,
  Apple,
  Droplet,
  Flame,
  Snowflake,
  Sun,
  Moon,
  Cloud,
  CloudRain,
  Wind,
  Zap,
  Lightbulb,
  Plug,
  Battery,
  Gauge,
  Bus,
  Train,
  Plane,
  Ship,
  Anchor,
  MapPin,
  Navigation,
  Compass,
  Globe,
  Camera,
  Video,
  Music,
  Mic,
  Headphones,
  Volume2,
  Speaker,
  Monitor,
  Laptop,
  Smartphone,
  Tablet,
  Wifi,
  Phone,
  Mail,
  MessageSquare,
  FileText,
  File,
  Folder,
  Archive,
  Printer,
  Scissors,
  PenTool,
  Brush,
  Palette,
  Code,
  Database,
  Server,
  HardDrive,
  Cpu,
  Bot,
  Sparkles,
  Wand2,
  PaintBucket,
  Ruler,
  Clipboard,
  Calendar,
  Clock,
  Timer,
  Flag,
  Tag,
  Tags,
  Award,
  Trophy,
  Crown,
  Star,
  ThumbsUp,
  ThumbsDown,
  Smile,
  Frown,
  Laugh,
  PartyPopper,
  Gift,
  Ticket,
  Film,
  Dumbbell,
  Bike,
  Footprints,
  Scroll,
  BookOpen,
  Book,
  GraduationCap,
  Pencil,
  Check,
  X,
  Plus,
  Minus,
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  Menu,
  List,
  Filter,
  Settings,
  Search,
  ZoomIn,
  ZoomOut,
  Maximize,
  Minimize2 as Minimize,
  ExternalLink,
  Share,
  Inbox,
  Save,
  Trash2,
  RotateCcw,
  RotateCw,
  RefreshCw,
  Play,
  Pause,
  Square,
  Circle,
  Triangle,
  Hexagon,
  CheckCircle,
  XCircle,
  AlertTriangle,
  AlertCircle,
  Info,
  HelpCircle,
  Eye,
  EyeOff,
  Lock,
  Unlock,
  Key,
  Shield,
  ShieldCheck,
  Bug,
  Target,
  Crosshair,
  Activity,
  Bed,
  DollarSign,
  TrendingUp,
  TrendingDown,
  Leaf,
  TreeDeciduous,
  Flower2,
  Grid,
  MoreVertical,
  MoreHorizontal,
  Layers,
  Box,
  Package,
  Truck as Truck2,
  Palmtree,
  Waves,
  Anchor as Anchor2,
  CameraOff,
  VideoOff,
  MicOff,
  VolumeX,
} from "lucide-react";

const ICON_LIST = [
  { name: "hammer", icon: Hammer },
  { name: "wrench", icon: Wrench },
  { name: "truck", icon: Truck },
  { name: "car", icon: Car },
  { name: "home", icon: Home },
  { name: "building", icon: Building },
  { name: "building2", icon: Building2 },
  { name: "user", icon: User },
  { name: "users", icon: Users },
  { name: "briefcase", icon: Briefcase },
  { name: "shoppingcart", icon: ShoppingCart },
  { name: "heart", icon: Heart },
  { name: "stethoscope", icon: Stethoscope },
  { name: "thermometer", icon: Thermometer },
  { name: "pill", icon: Pill },
  { name: "creditcard", icon: CreditCard },
  { name: "banknote", icon: Banknote },
  { name: "wallet", icon: Wallet },
  { name: "coffee", icon: Coffee },
  { name: "utensils", icon: UtensilsCrossed },
  { name: "pizza", icon: Pizza },
  { name: "wine", icon: Wine },
  { name: "cake", icon: Cake },
  { name: "apple", icon: Apple },
  { name: "droplet", icon: Droplet },
  { name: "flame", icon: Flame },
  { name: "snowflake", icon: Snowflake },
  { name: "sun", icon: Sun },
  { name: "moon", icon: Moon },
  { name: "cloud", icon: Cloud },
  { name: "cloudrain", icon: CloudRain },
  { name: "wind", icon: Wind },
  { name: "zap", icon: Zap },
  { name: "lightbulb", icon: Lightbulb },
  { name: "plug", icon: Plug },
  { name: "battery", icon: Battery },
  { name: "gauge", icon: Gauge },
  { name: "bus", icon: Bus },
  { name: "train", icon: Train },
  { name: "plane", icon: Plane },
  { name: "ship", icon: Ship },
  { name: "anchor", icon: Anchor },
  { name: "mappin", icon: MapPin },
  { name: "navigation", icon: Navigation },
  { name: "compass", icon: Compass },
  { name: "globe", icon: Globe },
  { name: "camera", icon: Camera },
  { name: "video", icon: Video },
  { name: "music", icon: Music },
  { name: "mic", icon: Mic },
  { name: "headphones", icon: Headphones },
  { name: "volume2", icon: Volume2 },
  { name: "speaker", icon: Speaker },
  { name: "monitor", icon: Monitor },
  { name: "laptop", icon: Laptop },
  { name: "smartphone", icon: Smartphone },
  { name: "tablet", icon: Tablet },
  { name: "wifi", icon: Wifi },
  { name: "phone", icon: Phone },
  { name: "mail", icon: Mail },
  { name: "messagesquare", icon: MessageSquare },
  { name: "filetext", icon: FileText },
  { name: "file", icon: File },
  { name: "folder", icon: Folder },
  { name: "archive", icon: Archive },
  { name: "printer", icon: Printer },
  { name: "scissors", icon: Scissors },
  { name: "pentool", icon: PenTool },
  { name: "brush", icon: Brush },
  { name: "palette", icon: Palette },
  { name: "code", icon: Code },
  { name: "database", icon: Database },
  { name: "server", icon: Server },
  { name: "harddrive", icon: HardDrive },
  { name: "cpu", icon: Cpu },
  { name: "bot", icon: Bot },
  { name: "sparkles", icon: Sparkles },
  { name: "wand2", icon: Wand2 },
  { name: "paintbucket", icon: PaintBucket },
  { name: "ruler", icon: Ruler },
  { name: "clipboard", icon: Clipboard },
  { name: "calendar", icon: Calendar },
  { name: "clock", icon: Clock },
  { name: "timer", icon: Timer },
  { name: "flag", icon: Flag },
  { name: "tag", icon: Tag },
  { name: "tags", icon: Tags },
  { name: "award", icon: Award },
  { name: "trophy", icon: Trophy },
  { name: "crown", icon: Crown },
  { name: "star", icon: Star },
  { name: "thumbsup", icon: ThumbsUp },
  { name: "thumbsdown", icon: ThumbsDown },
  { name: "smile", icon: Smile },
  { name: "frown", icon: Frown },
  { name: "laugh", icon: Laugh },
  { name: "partyPopper", icon: PartyPopper },
  { name: "gift", icon: Gift },
  { name: "ticket", icon: Ticket },
  { name: "film", icon: Film },
  { name: "dumbbell", icon: Dumbbell },
  { name: "bike", icon: Bike },
  { name: "footprints", icon: Footprints },
  { name: "scroll", icon: Scroll },
  { name: "bookopen", icon: BookOpen },
  { name: "book", icon: Book },
  { name: "graduationcap", icon: GraduationCap },
  { name: "pencil", icon: Pencil },
  { name: "check", icon: Check },
  { name: "x", icon: X },
  { name: "plus", icon: Plus },
  { name: "minus", icon: Minus },
  { name: "arrowup", icon: ArrowUp },
  { name: "arrowdown", icon: ArrowDown },
  { name: "arrowleft", icon: ArrowLeft },
  { name: "arrowright", icon: ArrowRight },
  { name: "menu", icon: Menu },
  { name: "list", icon: List },
  { name: "filter", icon: Filter },
  { name: "settings", icon: Settings },
  { name: "search", icon: Search },
  { name: "zoomin", icon: ZoomIn },
  { name: "zoomout", icon: ZoomOut },
  { name: "maximize", icon: Maximize },
  { name: "minimize", icon: Minimize },
  { name: "externallink", icon: ExternalLink },
  { name: "share", icon: Share },
  { name: "inbox", icon: Inbox },
  { name: "save", icon: Save },
  { name: "trash2", icon: Trash2 },
  { name: "rotateCcw", icon: RotateCcw },
  { name: "rotateCw", icon: RotateCw },
  { name: "refreshCw", icon: RefreshCw },
  { name: "play", icon: Play },
  { name: "pause", icon: Pause },
  { name: "square", icon: Square },
  { name: "circle", icon: Circle },
  { name: "triangle", icon: Triangle },
  { name: "hexagon", icon: Hexagon },
  { name: "checkcircle", icon: CheckCircle },
  { name: "xcircle", icon: XCircle },
  { name: "alerttriangle", icon: AlertTriangle },
  { name: "alertcircle", icon: AlertCircle },
  { name: "info", icon: Info },
  { name: "helpcircle", icon: HelpCircle },
  { name: "eye", icon: Eye },
  { name: "eyeoff", icon: EyeOff },
  { name: "lock", icon: Lock },
  { name: "unlock", icon: Unlock },
  { name: "key", icon: Key },
  { name: "shield", icon: Shield },
  { name: "shieldcheck", icon: ShieldCheck },
  { name: "bug", icon: Bug },
  { name: "target", icon: Target },
  { name: "crosshair", icon: Crosshair },
  { name: "activity", icon: Activity },
  { name: "bed", icon: Bed },
  { name: "dollarsign", icon: DollarSign },
  { name: "trendingup", icon: TrendingUp },
  { name: "trendingdown", icon: TrendingDown },
  { name: "leaf", icon: Leaf },
  { name: "tree", icon: TreeDeciduous },
  { name: "flower2", icon: Flower2 },
  { name: "grid", icon: Grid },
  { name: "morevertical", icon: MoreVertical },
  { name: "morehorizontal", icon: MoreHorizontal },
  { name: "layers", icon: Layers },
  { name: "box", icon: Box },
  { name: "package", icon: Package },
  { name: "truck2", icon: Truck2 },
  { name: "palmtree", icon: Palmtree },
  { name: "waves", icon: Waves },
  { name: "anchor2", icon: Anchor2 },
];

interface IconPickerProps {
  value: string;
  onChange: (icon: string) => void;
  label?: string;
}

export function IconPicker({ value, onChange, label = "Sélectionner une icône" }: IconPickerProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [search, setSearch] = useState("");

  const filteredIcons = search
    ? ICON_LIST.filter((item) =>
        item.name.toLowerCase().includes(search.toLowerCase())
      )
    : ICON_LIST;

  const selectedItem = ICON_LIST.find((item) => item.name === value);
  const SelectedIcon = selectedItem?.icon;

  return (
    <div className="space-y-2">
      {label && <label className="text-sm font-medium">{label}</label>}
      <div className="relative">
        <button
          type="button"
          onClick={() => setIsOpen(!isOpen)}
          className="w-full flex items-center justify-between px-3 py-2 border rounded-md hover:bg-gray-50"
        >
          <span className="flex items-center gap-2">
            {SelectedIcon ? (
              <SelectedIcon className="w-5 h-5" />
            ) : (
              <span className="text-gray-400 text-sm">Sélectionner...</span>
            )}
            {value && <span className="text-sm text-gray-500">{value}</span>}
          </span>
        </button>

        {isOpen && (
          <div className="absolute z-50 w-full mt-1 bg-white border rounded-md shadow-lg max-h-80 overflow-hidden">
            <div className="p-2 border-b">
              <input
                type="text"
                placeholder="Rechercher..."
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                className="w-full px-2 py-1 text-sm border rounded"
              />
            </div>
            <div className="overflow-y-auto max-h-60 p-2">
              <div className="flex flex-wrap gap-1">
                {filteredIcons.map(({ name, icon: IconComponent }) => (
                  <button
                    key={name}
                    type="button"
                    onClick={() => {
                      onChange(name);
                      setIsOpen(false);
                      setSearch("");
                    }}
                    className={`p-2 rounded hover:bg-gray-100 ${
                      value === name ? "bg-blue-100 text-blue-600" : ""
                    }`}
                    title={name}
                  >
                    <IconComponent className="w-4 h-4" />
                  </button>
                ))}
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

export { ICON_LIST };